import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
import asyncio
from typing import TypedDict
from pathlib import Path
import json

from code_validation import validate_code, CodeValidationError

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

MODEL = "Qwen/Qwen2.5-Coder-14B-Instruct"
tokenizer = AutoTokenizer.from_pretrained(MODEL)
model = AutoModelForCausalLM.from_pretrained(
    MODEL,
    dtype=torch.float16 if DEVICE.type == "cuda" else torch.float32,
    device_map="auto",
).eval()


VARIANTS = [
    "Write a highly optimized solution focusing on performance.",
    "Use a functional programming style where possible.",
    "Avoid using advanced libraries; rely on basic Python constructs.",
    "Use concise code, minimizing line count.",
]

OUTPUT_PATH = Path("output.jsonl")


VARIANTS_PER_PROBLEM = 3
CONCURRENCY = 1
YEARS = [2021, 2024]
DAYS = range(1, 25)


class Sample(TypedDict):
    """Base sample type for dataset code."""

    code: str
    label: str
    year: str
    day: str
    language: str


class LLMSample(Sample, total=True):
    """Sample type for code generated by LLMs."""

    model: str
    variant: str


class Job:
    year: int
    day: int
    variant_index: int

    def __init__(self, year: int, day: int, variant_index: int):
        self.year = year
        self.day = day
        self.variant_index = variant_index

    @property
    def id(self) -> str:
        return f"{self.year}-{self.day}-variant{self.variant_index}"


def generate_code(prompt: str, max_new_tokens: int = 512) -> str:
    messages = [
        {
            "role": "system",
            "content": "You are a helpful assistant for code generation.",
        },
        {"role": "user", "content": prompt},
    ]

    text = tokenizer.apply_chat_template(
        messages, add_generation_prompt=True, tokenize=False
    )

    chat_input = tokenizer(text, return_tensors="pt").to(DEVICE)

    with torch.no_grad():
        output = model.generate(
            **chat_input,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id,
        )
    generated_text = tokenizer.decode(output[0], skip_special_tokens=True)
    return generated_text.split("assistant")[-1].strip()


def read_file(path: str):
    try:
        with open(path, "r", encoding="utf-8") as f:
            return f.read()
    except FileNotFoundError:
        return None


def build_prompt(problem: str, variant: str) -> str:
    return f"""
You are solving an Advent of Code problem using Python.
Return ONLY valid Python code. You MUST ensure the code is syntactically correct and adheres to the problem requirements.
You MUST NOT include any explanations, comments, or text outside of the code. The code should be self-contained and executable.

Additional constraint:
{variant}

Problem:
{problem}
""".strip()


def load_completed_jobs(path: Path) -> set[str]:
    if not path.exists():
        return set()

    completed_ids: set[str] = set()
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            try:
                sample = json.loads(line)
                job_id = build_completion_id(
                    int(sample["year"]),
                    int(sample["day"]),
                    VARIANTS.index(sample["variant"]),
                )
                completed_ids.add(job_id)
            except (json.JSONDecodeError, KeyError):
                continue

    return completed_ids


def build_jobs() -> list[Job]:
    jobs: list[Job] = []
    for year in YEARS:
        for day in DAYS:
            for variant_index in range(VARIANTS_PER_PROBLEM):
                jobs.append(Job(year, day, variant_index))
    return jobs


def build_completion_id(year: int, day: int, variant_index: int) -> str:
    return f"{year}-{day}-variant{variant_index}"


def create_sample(year: int, day: int, variant: str, code: str) -> LLMSample:
    return LLMSample(
        year=str(year),
        day=str(day),
        label="machine",
        variant=variant,
        code=code,
        language="python",
        model=MODEL,
    )


async def get_valid_code(prompt: str, max_attempts: int = 3):
    content: str | None = None
    for attempt in range(max_attempts):
        try:
            response = generate_code(prompt)
            content = response.strip()

            validate_code(content)
            return content

        except CodeValidationError as e:
            print(f"Attempt {attempt + 1} failed: {e}. Recieved code:\n{content}\n")
            if attempt == max_attempts - 1:
                raise

    raise RuntimeError(
        "Unreachable: get_valid_code() reached max attempts without returning or raising."
    )


def create_jsonl_writer(path: Path):
    lock = asyncio.Lock()

    async def write(sample: LLMSample):
        line = json.dumps(sample) + "\n"
        async with lock:
            with open(path, "a", encoding="utf-8") as f:
                f.write(line)

    return write


async def process_job(writer, job: Job):
    folder = f"data/{job.year}/{job.day}"

    part1 = read_file(f"{folder}/part1.txt")
    part2 = read_file(f"{folder}/part2.txt")

    if not part1 or not part2:
        raise RuntimeError(f"Missing problem statement for {job.year} day {job.day}")

    problem = f"{part1}\n{part2}"
    variant = VARIANTS[job.variant_index]
    prompt = build_prompt(problem, variant)

    try:
        code = await get_valid_code(prompt)
        sample = create_sample(job.year, job.day, variant, code)
        await writer(sample)

    except CodeValidationError as e:
        print(
            f"Validation failed {job.year} day {job.day} variant {job.variant_index}: {e}"
        )
        raise


async def worker(
    name: str,
    writer,
    job_queue: asyncio.Queue[Job],
):
    while True:
        job = await job_queue.get()

        try:
            print(f"Worker {name} processing {job.id}")
            await process_job(writer, job)
            print(f"Worker {name} completed {job.id}")

        except Exception as e:
            print(f"Worker {name} encountered an error with {job.id}: {e}")

        finally:
            job_queue.task_done()


async def main() -> None:

    completed_ids = load_completed_jobs(OUTPUT_PATH)
    all_jobs = build_jobs()
    pending_jobs = [job for job in all_jobs if job.id not in completed_ids]
    print(
        f"Total jobs: {len(all_jobs)}, Completed: {len(completed_ids)}, Pending: {len(pending_jobs)}"
    )

    if not pending_jobs:
        print("No pending jobs to process. Exiting.")
        return

    job_queue: asyncio.Queue[Job] = asyncio.Queue()
    for job in pending_jobs:
        await job_queue.put(job)

    writer = create_jsonl_writer(OUTPUT_PATH)

    workers = [
        asyncio.create_task(worker(f"Worker-{i+1}", writer, job_queue))
        for i in range(CONCURRENCY)
    ]

    await job_queue.join()

    for w in workers:
        w.cancel()

    await asyncio.gather(*workers, return_exceptions=True)


if __name__ == "__main__":
    asyncio.run(main())
