import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
from typing import TypedDict
from pathlib import Path
import json
import re
from dataclasses import dataclass

from code_validation import validate_code, CodeValidationError

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

MODEL = "Qwen/Qwen2.5-Coder-14B-Instruct"
tokenizer = AutoTokenizer.from_pretrained(MODEL)
model = AutoModelForCausalLM.from_pretrained(
    MODEL,
    torch_dtype=torch.float16,
    device_map="auto",
)


VARIANTS = [
    "Write a highly optimized solution focusing on performance.",
    "Use a functional programming style where possible.",
    "Avoid using advanced libraries; rely on basic Python constructs.",
    "Use concise code, minimizing line count.",
]

SYSTEM_PROMPT = (
    "You are a Python code generator.\n"
    "Output raw Python source code only.\n"
    "Do NOT use markdown.\n"
    "Do NOT wrap the code in triple backticks.\n"
    "Do NOT include explanations.\n"
    "Do NOT include comments outside the code.\n"
    "The first character of your response must be valid Python code."
)
OUTPUT_PATH = Path("output.jsonl")


VARIANTS_PER_PROBLEM = 3
YEARS = [2021, 2024]
DAYS = range(1, 25)


class Sample(TypedDict):
    """Base sample type for dataset code."""

    code: str
    label: str
    year: str
    day: str
    language: str


class LLMSample(Sample, total=True):
    """Sample type for code generated by LLMs."""

    model: str
    variant: str


@dataclass(frozen=True)
class Job:
    year: int
    day: int
    variant: str
    prompt: str

    @property
    def id(self) -> str:
        return f"{self.year}-{self.day}-{self.variant}"


def strip_code_fences(text: str) -> str:
    text = text.strip()

    text = re.sub(r"^```python\s*", "", text)
    text = re.sub(r"^```\s*", "", text)
    text = re.sub(r"\s*```$", "", text)

    return text.strip()


@torch.inference_mode()
def generate_batch(prompts: list[str], max_new_tokens: int = 1024) -> list[str]:
inputs = tokenizer(prompts, return_tensors="pt", padding=True, return_attention_mask=True)
inputs = {k: v.to(model.device) for k, v in inputs.items()}

outputs = model.generate(
    **inputs,
    max_new_tokens=max_new_tokens,
    do_sample=False,
    pad_token_id=tokenizer.eos_token_id,
)

    prompt_lengths = inputs["attention_mask"].sum(dim=1)

    codes = [
        tokenizer.decode(
            output[prompt_len:],
            skip_special_tokens=True,
        )
        for output, prompt_len in zip(outputs, prompt_lengths)
    ]

return [strip_code_fences(code) for code in codes]

def run_batch(jobs: list[Job], batch_size: int) -> list[tuple[Job, str]]:
    results: list[tuple[Job, str]] = []

    for i in range(0, len(jobs), batch_size):
        batch = jobs[i : i + batch_size]
        prompts = [j.prompt for j in batch]

        codes = generate_batch(prompts)
        results.extend((job, code) for job, code in zip(batch, codes, strict=True))

    return results


def validate_batch(results: list[tuple[Job, str]]):
    valid: list[tuple[Job, str]] = []
    failed: list[Job] = []

    for job, code in results:
        try:
            validate_code(code)
            valid.append((job, code))
        except CodeValidationError:
            failed.append(job)

    return valid, failed


def retry_failed(failed: list[Job], batch_size: int) -> list[tuple[Job, str]]:
    if not failed:
        return []

    return run_batch(failed, batch_size)


def run_jobs(jobs: list[Job], max_retries: int = 3, batch_size: int = 8):
    results = run_batch(jobs, batch_size)

    valid, failed = validate_batch(results)
    all_valid = valid

    for i in range(max_retries):
        if not failed:
            break

        print(f"Retry {i+1}: {len(failed)} failed")

        retry_results = retry_failed(failed, batch_size)
        valid_retry, failed_retry = validate_batch(retry_results)

        failed = failed_retry

        all_valid.extend(valid_retry)

    return all_valid


def read_file(path: str):
    try:
        with open(path, "r", encoding="utf-8") as f:
            return f.read()
    except FileNotFoundError:
        return None


def build_prompt(problem: str, variant: str) -> str:
    return f"""
You are solving an Advent of Code problem using Python.
Return ONLY valid Python code. You MUST ensure the code is syntactically correct and adheres to the problem requirements.
You MUST NOT include any explanations, comments, or text outside of the code. The code should be self-contained and executable.

Additional constraint:
{variant}

Problem:
{problem}
""".strip()


def load_completed_jobs(path: Path) -> set[str]:
    if not path.exists():
        return set()

    completed_ids: set[str] = set()
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            try:
                sample = json.loads(line)
                job_id = f"{sample['year']}-{sample['day']}-{sample['variant']}"
                completed_ids.add(job_id)
            except (json.JSONDecodeError, KeyError):
                continue

    return completed_ids


def create_sample(result: tuple[Job, str]) -> LLMSample:
    job, code = result
    return LLMSample(
        year=str(job.year),
        day=str(job.day),
        label="machine",
        variant=job.variant,
        code=code,
        language="python",
        model=MODEL,
    )


def write_all_samples(path: Path, samples: list[LLMSample]) -> None:
    with open(path, "a", encoding="utf-8") as f:
        for sample in samples:
            json.dump(sample, f)
            f.write("\n")


def build_jobs() -> list[Job]:
    jobs: list[Job] = []

    for year in YEARS:
        for day in DAYS:
            part1 = read_file(f"problems/{year}/{day}/part1.txt")
            part2 = read_file(f"problems/{year}/{day}/part2.txt")
            problem = "\n\n".join(filter(None, [part1, part2]))
            if not problem:
                continue

            for i in range(VARIANTS_PER_PROBLEM):
                variant = VARIANTS[i % len(VARIANTS)]
                prompt = build_prompt(problem, variant)

                jobs.append(Job(year, day, variant, prompt))

    return jobs


def main() -> None:
    completed = load_completed_jobs(OUTPUT_PATH)
    all_jobs = build_jobs()

    jobs = [j for j in all_jobs if j.id not in completed]

    print(f"Pending jobs: {len(jobs)}")

    final = run_jobs(jobs, max_retries=3, batch_size=8)

    write_all_samples(
        OUTPUT_PATH,
        [create_sample(result) for result in final],
    )


if __name__ == "__main__":
    main()
