from typing import Optional, TypedDict


class Sample(TypedDict):
    """Base sample type for dataset code."""

    code: str
    label: str
    year: str
    day: str
    language: str


class LLMSample(Sample, total=True):
    """Sample type for code generated by LLMs."""

    model: str
    prompt: str
    code_variant: str
    style_variant: str


class HumanSample(Sample, total=True):
    """Sample type for human-written code."""

    repo: str
    path: str


type Samples = list[LLMSample | HumanSample]


class GitHubRepo(TypedDict):
    name: str
    full_name: str
    ssh_url: str
    language: Optional[str]
    description: Optional[str]
    topics: list[str]
